name: Let's Encrypt v2
description: Trusted SSL certificates at zero cost
version: 2.0.0
category: Security
maintainer: smujaddid
license: Apache License 2.0
projectURL: https://github.com/smujaddid/rancher-letsencrypt
